/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos_app_cangjie_entry

import kit.PerformanceAnalysisKit.Hilog
import ohos.arkui.component.*
import ohos.arkui.state_management.*
import ohos.arkui.state_macro_manage.*
import std.convert.*
import ohos.base.{LengthProp, Length, Color,LengthType}



@Builder
func Builder_bindMenu() {
    Column {
        Text("Builder_Extend_RedFont").fontSize(20).fontColor(Color.Red).id("Builder_bindMenu_RedFont")
        Text("Builder_Extend_BlueFont").fontSize(20).fontColor(Color.Blue).id("Builder_bindMenu_BlueFont")
    }
}

extend Button {
    func userModifier(customView: CustomView) {
        this.bindMenu(builder: bind(Builder_bindMenu,customView))
    }
}

@Entry
@Component
class View_Builder_Extend {
    func build() {
        Row() {
            Column(space:50) {
                Button("Button-bindMenu-LongClick").userModifier(this).id("bindMenu")
                Button("Button-bindContextMenu-LongPress")
                .bindContextMenu(builder:Builder_bindMenu,  responseType:ResponseType.LongPress,options:ContextMenuOptions(
                        enableArrow: true,
                        placement: Placement.Bottom,
                        arrowOffset: 20.vp
                    ))
                    //.bindContextMenu(builder: )
                    .id("bindContextMenu")
            }.width(100.percent)
        }.height(100.percent)
    }
}
