/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos_app_cangjie_entry
 let _ = testsuite()
func testsuite(): Unit   {
registerTestSuite("testBundleInfo_installTime_1", { =>testBundleInfo_installTime_1()
})
registerTestSuite("testBundleInfo_installTime_2", { =>testBundleInfo_installTime_2()
})
registerTestSuite("testBundleInfo_installTime_3", { =>testBundleInfo_installTime_3()
})
registerTestSuite("testBundleInfo_installTime_4", { =>testBundleInfo_installTime_4()
})
registerTestSuite("testBundleInfo_installTime_5", { =>testBundleInfo_installTime_5()
})
registerTestSuite("testBundleInfo_installTime_6", { =>testBundleInfo_installTime_6()
})
registerTestSuite("testBundleInfo_installTime_7", { =>testBundleInfo_installTime_7()
})
registerTestSuite("testBundleInfo_installTime_8", { =>testBundleInfo_installTime_8()
})
registerTestSuite("testBundleInfo_installTime_9", { =>testBundleInfo_installTime_9()
})
registerTestSuite("testBundleInfo_installTime_10", { =>testBundleInfo_installTime_10()
})
registerTestSuite("testBundleInfo_installTime_11", { =>testBundleInfo_installTime_11()
})
registerTestSuite("testBundleInfo_installTime_12", { =>testBundleInfo_installTime_12()
})
registerTestSuite("testBundleInfo_installTime_13", { =>testBundleInfo_installTime_13()
})
registerTestSuite("testBundleInfo_installTime_14", { =>testBundleInfo_installTime_14()
})
registerTestSuite("testBundleInfo_installTime_15", { =>testBundleInfo_installTime_15()
})
registerTestSuite("testBundleInfo_installTime_16", { =>testBundleInfo_installTime_16()
})
registerTestSuite("testBundleInfo_installTime_17", { =>testBundleInfo_installTime_17()
})
registerTestSuite("testBundleInfo_installTime_18", { =>testBundleInfo_installTime_18()
})
}
