/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos_app_cangjie_entry

import std.unittest.*
import std.unittest.common.*
import std.unittest.testmacro.*
import std.collection.*
import ohos.base.*
import stdx.encoding.json.*
import ohos.app.ability.ability_delegator_registry.*
import kit.PerformanceAnalysisKit.Hilog

@Test
class testExecuteShellCommand_1 {
    /*
     * @tc.number    : Sub_Cangjie_ability_delegator_registry_executeShellCommand_0100
     * @tc.name      : TestCase_1
     * @tc.desc      : fail to execute command
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_1(): Unit {
        Hilog.info(0,"cangjie","testcase TestCase_1 begins.")
        Hilog.info(0,"cangjie","define local variable result")
        let result = AbilityDelegatorRegistry.getAbilityDelegator().executeShellCommand("", timeoutSecs:-9223372036854775808i64)
        @Expect(true)
        Hilog.info(0,"cangjie","testcase TestCase_1 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_ability_delegator_registry_executeShellCommand_0200
     * @tc.name      : TestCase_2
     * @tc.desc      : fail to execute command
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_2(): Unit {
        Hilog.info(0,"cangjie","testcase TestCase_2 begins.")
        Hilog.info(0,"cangjie","define local variable result")
        let result = AbilityDelegatorRegistry.getAbilityDelegator().executeShellCommand(" ", timeoutSecs:-114514i64)
        @Expect(true)
        Hilog.info(0,"cangjie","testcase TestCase_2 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_ability_delegator_registry_executeShellCommand_0300
     * @tc.name      : TestCase_3
     * @tc.desc      : fail to execute command
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3(): Unit {
        Hilog.info(0,"cangjie","testcase TestCase_3 begins.")
        Hilog.info(0,"cangjie","define local variable result")
        let result = AbilityDelegatorRegistry.getAbilityDelegator().executeShellCommand("	", timeoutSecs:-1i64)
        @Expect(true)
        Hilog.info(0,"cangjie","testcase TestCase_3 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_ability_delegator_registry_executeShellCommand_0400
     * @tc.name      : TestCase_4
     * @tc.desc      : fail to execute command
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_4(): Unit {
        Hilog.info(0,"cangjie","testcase TestCase_4 begins.")
        Hilog.info(0,"cangjie","define local variable result")
        let result = AbilityDelegatorRegistry.getAbilityDelegator().executeShellCommand(" ", timeoutSecs:0i64)
        @Expect(true)
        Hilog.info(0,"cangjie","testcase TestCase_4 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_ability_delegator_registry_executeShellCommand_0500
     * @tc.name      : TestCase_5
     * @tc.desc      : fail to execute command
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_5(): Unit {
        Hilog.info(0,"cangjie","testcase TestCase_5 begins.")
        Hilog.info(0,"cangjie","define local variable result")
        let result = AbilityDelegatorRegistry.getAbilityDelegator().executeShellCommand("0", timeoutSecs:1i64)
        @Expect(true)
        Hilog.info(0,"cangjie","testcase TestCase_5 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_ability_delegator_registry_executeShellCommand_0600
     * @tc.name      : TestCase_6
     * @tc.desc      : fail to execute command
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_6(): Unit {
        Hilog.info(0,"cangjie","testcase TestCase_6 begins.")
        Hilog.info(0,"cangjie","define local variable result")
        let result = AbilityDelegatorRegistry
            .getAbilityDelegator()
            .executeShellCommand("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", timeoutSecs:114514i64)
        @Expect(true)
        Hilog.info(0,"cangjie","testcase TestCase_6 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_ability_delegator_registry_executeShellCommand_0700
     * @tc.name      : TestCase_7
     * @tc.desc      : fail to execute command
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_7(): Unit {
        Hilog.info(0,"cangjie","testcase TestCase_7 begins.")
        Hilog.info(0,"cangjie","define local variable result")
        let result = AbilityDelegatorRegistry.getAbilityDelegator().executeShellCommand("ps", timeoutSecs:9223372036854775807i64)
        Hilog.info(0,"cangjie","testcase TestCase_7 ends.")
    }
}
