/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos_app_cangjie_entry
 let _ = testsuite()
func testsuite(): Unit   {
registerTestSuite("testBundleInfo_name_1", { =>testBundleInfo_name_1()
})
registerTestSuite("testBundleInfo_name_2", { =>testBundleInfo_name_2()
})
registerTestSuite("testBundleInfo_name_3", { =>testBundleInfo_name_3()
})
registerTestSuite("testBundleInfo_name_4", { =>testBundleInfo_name_4()
})
registerTestSuite("testBundleInfo_name_5", { =>testBundleInfo_name_5()
})
registerTestSuite("testBundleInfo_name_6", { =>testBundleInfo_name_6()
})
registerTestSuite("testBundleInfo_name_7", { =>testBundleInfo_name_7()
})
registerTestSuite("testBundleInfo_name_8", { =>testBundleInfo_name_8()
})
registerTestSuite("testBundleInfo_name_9", { =>testBundleInfo_name_9()
})
registerTestSuite("testBundleInfo_name_10", { =>testBundleInfo_name_10()
})
registerTestSuite("testBundleInfo_name_11", { =>testBundleInfo_name_11()
})
registerTestSuite("testBundleInfo_name_12", { =>testBundleInfo_name_12()
})
registerTestSuite("testBundleInfo_name_13", { =>testBundleInfo_name_13()
})
registerTestSuite("testBundleInfo_name_14", { =>testBundleInfo_name_14()
})
registerTestSuite("testBundleInfo_name_15", { =>testBundleInfo_name_15()
})
registerTestSuite("testBundleInfo_name_16", { =>testBundleInfo_name_16()
})
registerTestSuite("testBundleInfo_name_17", { =>testBundleInfo_name_17()
})
registerTestSuite("testBundleInfo_name_18", { =>testBundleInfo_name_18()
})
}
