/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos_app_cangjie_entry

let _ = testsuite()

func testsuite(): Unit {

    registerTestSuite("testStartTrace_35", {
        => testStartTrace_35()
    })
    registerTestSuite("testStartTrace_36", {
        => testStartTrace_36()
    })
    registerTestSuite("testStartTrace_37", {
        => testStartTrace_37()
    })
    registerTestSuite("testStartTrace_38", {
        => testStartTrace_38()
    })
    registerTestSuite("testStartTrace_39", {
        => testStartTrace_39()
    })
    registerTestSuite("testStartTrace_40", {
        => testStartTrace_40()
    })
    registerTestSuite("testStartTrace_41", {
        => testStartTrace_41()
    })
    registerTestSuite("testStartTrace_42", {
        => testStartTrace_42()
    })
    registerTestSuite("testStartTrace_43", {
        => testStartTrace_43()
    })
    registerTestSuite("testStartTrace_44", {
        => testStartTrace_44()
    })
    registerTestSuite("testStartTrace_45", {
        => testStartTrace_45()
    })
    registerTestSuite("testStartTrace_46", {
        => testStartTrace_46()
    })
    registerTestSuite("testStartTrace_47", {
        => testStartTrace_47()
    })
    registerTestSuite("testStartTrace_48", {
        => testStartTrace_48()
    })
    registerTestSuite("testStartTrace_49", {
        => testStartTrace_49()
    })
    registerTestSuite("testStartTrace_50", {
        => testStartTrace_50()
    })
    registerTestSuite("testStartTrace_51", {
        => testStartTrace_51()
    })
    registerTestSuite("testStartTrace_52", {
        => testStartTrace_52()
    })
    registerTestSuite("testStartTrace_53", {
        => testStartTrace_53()
    })

}
