/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos_app_cangjie_entry
 let _ = testsuite()
func testsuite(): Unit   {
registerTestSuite("testModuleInfo_mainElemententry_1", { =>testModuleInfo_mainElemententry_1()
})
registerTestSuite("testModuleInfo_mainElemententry_2", { =>testModuleInfo_mainElemententry_2()
})
registerTestSuite("testModuleInfo_mainElemententry_3", { =>testModuleInfo_mainElemententry_3()
})
registerTestSuite("testModuleInfo_mainElemententry_4", { =>testModuleInfo_mainElemententry_4()
})
registerTestSuite("testModuleInfo_mainElemententry_5", { =>testModuleInfo_mainElemententry_5()
})
registerTestSuite("testModuleInfo_mainElemententry_6", { =>testModuleInfo_mainElemententry_6()
})
registerTestSuite("testModuleInfo_mainElemententry_7", { =>testModuleInfo_mainElemententry_7()
})
registerTestSuite("testModuleInfo_mainElemententry_8", { =>testModuleInfo_mainElemententry_8()
})
registerTestSuite("testModuleInfo_mainElemententry_9", { =>testModuleInfo_mainElemententry_9()
})
registerTestSuite("testModuleInfo_mainElemententry_10", { =>testModuleInfo_mainElemententry_10()
})
registerTestSuite("testModuleInfo_mainElemententry_11", { =>testModuleInfo_mainElemententry_11()
})
registerTestSuite("testModuleInfo_mainElemententry_12", { =>testModuleInfo_mainElemententry_12()
})
registerTestSuite("testModuleInfo_mainElemententry_13", { =>testModuleInfo_mainElemententry_13()
})
registerTestSuite("testModuleInfo_mainElemententry_14", { =>testModuleInfo_mainElemententry_14()
})
registerTestSuite("testModuleInfo_mainElemententry_15", { =>testModuleInfo_mainElemententry_15()
})
registerTestSuite("testModuleInfo_mainElemententry_16", { =>testModuleInfo_mainElemententry_16()
})
registerTestSuite("testModuleInfo_mainElemententry_17", { =>testModuleInfo_mainElemententry_17()
})
registerTestSuite("testModuleInfo_mainElemententry_18", { =>testModuleInfo_mainElemententry_18()
})
}
