/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos_app_cangjie_entry

import std.unittest.*
import std.unittest.common.*
import std.unittest.testmacro.*
import std.collection.*
import ohos.base.*
import stdx.encoding.json.*
import ohos.hi_trace_meter.*
import kit.PerformanceAnalysisKit.Hilog

@Test
class testStartTrace_34 {
    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_330100
     * @tc.name      : TestCase_3301
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "100"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3301(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3301 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 100i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3301 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_330200
     * @tc.name      : TestCase_3302
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "101"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3302(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3302 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 101i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3302 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_330300
     * @tc.name      : TestCase_3303
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "102"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3303(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3303 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 102i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3303 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_330400
     * @tc.name      : TestCase_3304
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "103"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3304(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3304 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 103i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3304 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_330500
     * @tc.name      : TestCase_3305
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "104"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3305(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3305 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 104i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3305 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_330600
     * @tc.name      : TestCase_3306
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "105"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3306(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3306 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 105i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3306 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_330700
     * @tc.name      : TestCase_3307
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "106"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3307(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3307 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 106i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3307 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_330800
     * @tc.name      : TestCase_3308
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "107"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3308(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3308 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 107i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3308 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_330900
     * @tc.name      : TestCase_3309
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "108"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3309(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3309 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 108i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3309 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_331000
     * @tc.name      : TestCase_3310
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "109"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3310(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3310 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 109i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3310 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_331100
     * @tc.name      : TestCase_3311
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "110"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3311(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3311 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 110i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3311 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_331200
     * @tc.name      : TestCase_3312
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "111"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3312(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3312 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 111i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3312 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_331300
     * @tc.name      : TestCase_3313
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "112"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3313(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3313 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 112i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3313 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_331400
     * @tc.name      : TestCase_3314
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "113"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3314(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3314 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 113i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3314 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_331500
     * @tc.name      : TestCase_3315
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "114"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3315(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3315 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 114i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3315 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_331600
     * @tc.name      : TestCase_3316
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "115"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3316(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3316 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 115i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3316 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_331700
     * @tc.name      : TestCase_3317
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "116"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3317(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3317 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 116i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3317 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_331800
     * @tc.name      : TestCase_3318
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "117"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3318(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3318 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 117i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3318 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_331900
     * @tc.name      : TestCase_3319
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "118"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3319(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3319 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 118i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3319 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_332000
     * @tc.name      : TestCase_3320
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "119"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3320(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3320 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 119i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3320 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_332100
     * @tc.name      : TestCase_3321
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "120"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3321(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3321 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 120i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3321 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_332200
     * @tc.name      : TestCase_3322
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "121"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3322(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3322 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 121i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3322 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_332300
     * @tc.name      : TestCase_3323
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "122"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3323(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3323 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 122i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3323 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_332400
     * @tc.name      : TestCase_3324
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "123"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3324(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3324 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 123i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3324 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_332500
     * @tc.name      : TestCase_3325
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "124"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3325(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3325 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 124i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3325 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_332600
     * @tc.name      : TestCase_3326
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "125"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3326(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3326 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 125i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3326 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_332700
     * @tc.name      : TestCase_3327
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "126"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3327(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3327 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 126i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3327 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_332800
     * @tc.name      : TestCase_3328
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "127"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3328(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3328 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 127i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3328 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_332900
     * @tc.name      : TestCase_3329
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "128"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3329(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3329 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 128i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3329 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_333000
     * @tc.name      : TestCase_3330
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "129"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3330(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3330 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 129i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3330 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_333100
     * @tc.name      : TestCase_3331
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "114514"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3331(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3331 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 114514i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3331 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_333200
     * @tc.name      : TestCase_3332
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "5", taskId:  "2147483647"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3332(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3332 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("5", 2147483647i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3332 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_333300
     * @tc.name      : TestCase_3333
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-2147483648"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3333(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3333 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -2147483648i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3333 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_333400
     * @tc.name      : TestCase_3334
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-114514"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3334(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3334 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -114514i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3334 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_333500
     * @tc.name      : TestCase_3335
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-30"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3335(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3335 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -30i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3335 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_333600
     * @tc.name      : TestCase_3336
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-29"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3336(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3336 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -29i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3336 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_333700
     * @tc.name      : TestCase_3337
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-28"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3337(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3337 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -28i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3337 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_333800
     * @tc.name      : TestCase_3338
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-27"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3338(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3338 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -27i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3338 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_333900
     * @tc.name      : TestCase_3339
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-26"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3339(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3339 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -26i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3339 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_334000
     * @tc.name      : TestCase_3340
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-25"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3340(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3340 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -25i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3340 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_334100
     * @tc.name      : TestCase_3341
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-24"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3341(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3341 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -24i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3341 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_334200
     * @tc.name      : TestCase_3342
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-23"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3342(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3342 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -23i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3342 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_334300
     * @tc.name      : TestCase_3343
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-22"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3343(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3343 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -22i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3343 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_334400
     * @tc.name      : TestCase_3344
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-21"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3344(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3344 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -21i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3344 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_334500
     * @tc.name      : TestCase_3345
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-20"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3345(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3345 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -20i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3345 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_334600
     * @tc.name      : TestCase_3346
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-19"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3346(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3346 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -19i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3346 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_334700
     * @tc.name      : TestCase_3347
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-18"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3347(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3347 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -18i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3347 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_334800
     * @tc.name      : TestCase_3348
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-17"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3348(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3348 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -17i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3348 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_334900
     * @tc.name      : TestCase_3349
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-16"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3349(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3349 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -16i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3349 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_335000
     * @tc.name      : TestCase_3350
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-15"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3350(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3350 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -15i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3350 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_335100
     * @tc.name      : TestCase_3351
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-14"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3351(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3351 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -14i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3351 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_335200
     * @tc.name      : TestCase_3352
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-13"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3352(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3352 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -13i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3352 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_335300
     * @tc.name      : TestCase_3353
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-12"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3353(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3353 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -12i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3353 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_335400
     * @tc.name      : TestCase_3354
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-11"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3354(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3354 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -11i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3354 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_335500
     * @tc.name      : TestCase_3355
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-10"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3355(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3355 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -10i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3355 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_335600
     * @tc.name      : TestCase_3356
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-9"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3356(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3356 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -9i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3356 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_335700
     * @tc.name      : TestCase_3357
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-8"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3357(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3357 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -8i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3357 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_335800
     * @tc.name      : TestCase_3358
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-7"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3358(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3358 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -7i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3358 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_335900
     * @tc.name      : TestCase_3359
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-6"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3359(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3359 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -6i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3359 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_336000
     * @tc.name      : TestCase_3360
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-5"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3360(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3360 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -5i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3360 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_336100
     * @tc.name      : TestCase_3361
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-4"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3361(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3361 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -4i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3361 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_336200
     * @tc.name      : TestCase_3362
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-3"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3362(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3362 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -3i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3362 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_336300
     * @tc.name      : TestCase_3363
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-2"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3363(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3363 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -2i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3363 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_336400
     * @tc.name      : TestCase_3364
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "-1"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3364(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3364 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", -1i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3364 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_336500
     * @tc.name      : TestCase_3365
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "0"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3365(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3365 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 0i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3365 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_336600
     * @tc.name      : TestCase_3366
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "1"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3366(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3366 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 1i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3366 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_336700
     * @tc.name      : TestCase_3367
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "2"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3367(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3367 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 2i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3367 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_336800
     * @tc.name      : TestCase_3368
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "3"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3368(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3368 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 3i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3368 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_336900
     * @tc.name      : TestCase_3369
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "4"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3369(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3369 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 4i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3369 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_337000
     * @tc.name      : TestCase_3370
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "5"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3370(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3370 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 5i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3370 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_337100
     * @tc.name      : TestCase_3371
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "6"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3371(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3371 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 6i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3371 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_337200
     * @tc.name      : TestCase_3372
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "7"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3372(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3372 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 7i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3372 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_337300
     * @tc.name      : TestCase_3373
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "8"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3373(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3373 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 8i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3373 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_337400
     * @tc.name      : TestCase_3374
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "9"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3374(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3374 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 9i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3374 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_337500
     * @tc.name      : TestCase_3375
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "10"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3375(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3375 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 10i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3375 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_337600
     * @tc.name      : TestCase_3376
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "11"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3376(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3376 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 11i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3376 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_337700
     * @tc.name      : TestCase_3377
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "12"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3377(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3377 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 12i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3377 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_337800
     * @tc.name      : TestCase_3378
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "13"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3378(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3378 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 13i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3378 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_337900
     * @tc.name      : TestCase_3379
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "14"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3379(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3379 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 14i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3379 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_338000
     * @tc.name      : TestCase_3380
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "15"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3380(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3380 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 15i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3380 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_338100
     * @tc.name      : TestCase_3381
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "16"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3381(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3381 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 16i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3381 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_338200
     * @tc.name      : TestCase_3382
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "17"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3382(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3382 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 17i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3382 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_338300
     * @tc.name      : TestCase_3383
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "18"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3383(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3383 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 18i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3383 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_338400
     * @tc.name      : TestCase_3384
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "19"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3384(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3384 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 19i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3384 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_338500
     * @tc.name      : TestCase_3385
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "20"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3385(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3385 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 20i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3385 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_338600
     * @tc.name      : TestCase_3386
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "21"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3386(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3386 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 21i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3386 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_338700
     * @tc.name      : TestCase_3387
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "22"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3387(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3387 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 22i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3387 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_338800
     * @tc.name      : TestCase_3388
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "23"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3388(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3388 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 23i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3388 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_338900
     * @tc.name      : TestCase_3389
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "24"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3389(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3389 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 24i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3389 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_339000
     * @tc.name      : TestCase_3390
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "25"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3390(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3390 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 25i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3390 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_339100
     * @tc.name      : TestCase_3391
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "26"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3391(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3391 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 26i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3391 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_339200
     * @tc.name      : TestCase_3392
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "27"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3392(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3392 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 27i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3392 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_339300
     * @tc.name      : TestCase_3393
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "28"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3393(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3393 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 28i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3393 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_339400
     * @tc.name      : TestCase_3394
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "29"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3394(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3394 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 29i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3394 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_339500
     * @tc.name      : TestCase_3395
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "30"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3395(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3395 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 30i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3395 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_339600
     * @tc.name      : TestCase_3396
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "31"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3396(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3396 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 31i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3396 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_339700
     * @tc.name      : TestCase_3397
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "32"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3397(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3397 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 32i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3397 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_339800
     * @tc.name      : TestCase_3398
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "33"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3398(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3398 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 33i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3398 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_339900
     * @tc.name      : TestCase_3399
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "100"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3399(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3399 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 100i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3399 ends.")
    }

    /*
     * @tc.number    : Sub_Cangjie_testStartTrace_startTrace_340000
     * @tc.name      : TestCase_3400
     * @tc.desc      : Mark the start of a pre-tracked time-consuming task. name: "6", taskId:  "101"
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : Level 0
     */
    @TestCase
    @Tag[APILevel12, TestLevel0]
    func TestCase_3400(): Unit {
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3400 begins.")
        Hilog.info(0u32, "cangjietest", "startTrace")
        HiTraceMeter.startTrace("6", 101i32)
        @Assert(true)
        Hilog.info(0u32, "cangjietest", "testcase TestCase_3400 ends.")
    }
}
